-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_code character varying NOT NULL UNIQUE,
  legal_name character varying NOT NULL,
  display_name character varying NOT NULL,
  registration_number character varying,
  gstin character varying,
  pan character varying,
  email character varying,
  phone character varying,
  website character varying,
  address_line1 text,
  city character varying,
  state character varying,
  pincode character varying,
  country character varying NOT NULL DEFAULT 'India'::character varying,
  timezone character varying NOT NULL DEFAULT 'Asia/Kolkata'::character varying,
  currency character varying NOT NULL DEFAULT 'INR'::character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  trade_name character varying DEFAULT 'Loan On Tip'::character varying,
  tax_id character varying,
  logo_url text,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_code character varying NOT NULL,
  name character varying NOT NULL,
  location_type character varying NOT NULL DEFAULT 'OFFICE'::character varying,
  address_line1 text,
  city character varying,
  state character varying,
  pincode character varying,
  latitude numeric,
  longitude numeric,
  attendance_radius_meters integer NOT NULL DEFAULT 150 CHECK (attendance_radius_meters >= 25 AND attendance_radius_meters <= 5000),
  timezone character varying NOT NULL DEFAULT 'Asia/Kolkata'::character varying,
  contact_name character varying,
  contact_phone character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.departments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  department_code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  head_employee_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departments_pkey PRIMARY KEY (id),
  CONSTRAINT departments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT fk_dept_head FOREIGN KEY (head_employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  department_id uuid,
  location_id uuid,
  team_code character varying NOT NULL,
  name character varying NOT NULL,
  manager_employee_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT teams_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT teams_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT fk_team_manager FOREIGN KEY (manager_employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.designations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  designation_code character varying NOT NULL,
  name character varying NOT NULL,
  level integer,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT designations_pkey PRIMARY KEY (id),
  CONSTRAINT designations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.employment_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT employment_types_pkey PRIMARY KEY (id),
  CONSTRAINT employment_types_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid,
  shift_code character varying NOT NULL,
  name character varying NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  break_minutes integer NOT NULL DEFAULT 0,
  grace_minutes integer NOT NULL DEFAULT 15,
  half_day_after_minutes integer NOT NULL DEFAULT 240,
  full_day_after_minutes integer NOT NULL DEFAULT 360,
  minimum_work_minutes integer NOT NULL DEFAULT 240,
  overtime_after_minutes integer NOT NULL DEFAULT 540,
  is_overnight boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shifts_pkey PRIMARY KEY (id),
  CONSTRAINT shifts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT shifts_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.shift_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  shift_id uuid NOT NULL,
  effective_from date NOT NULL,
  effective_to date,
  is_current boolean NOT NULL DEFAULT true,
  assigned_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shift_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT shift_assignments_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT fk_shift_emp FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT fk_shift_by FOREIGN KEY (assigned_by) REFERENCES public.employees(id)
);
CREATE TABLE public.holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid,
  holiday_date date NOT NULL,
  name character varying NOT NULL,
  holiday_type character varying NOT NULL DEFAULT 'NATIONAL'::character varying,
  is_optional boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT holidays_pkey PRIMARY KEY (id),
  CONSTRAINT holidays_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT holidays_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.weekly_off_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid,
  day_of_week smallint NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  week_number smallint CHECK (week_number >= 1 AND week_number <= 5),
  is_off boolean NOT NULL DEFAULT true,
  effective_from date NOT NULL,
  effective_to date,
  CONSTRAINT weekly_off_rules_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_off_rules_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT weekly_off_rules_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid UNIQUE,
  employee_id uuid,
  company_id uuid,
  email character varying,
  phone character varying,
  avatar_url text,
  last_login_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT fk_profile_emp FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  employee_code character varying DEFAULT NULL::character varying,
  first_name character varying NOT NULL,
  middle_name character varying,
  last_name character varying NOT NULL,
  display_name character varying,
  gender character varying,
  date_of_birth date,
  profile_photo_url text,
  joining_date date,
  confirmation_date date,
  employment_type_id uuid,
  department_id uuid,
  designation_id uuid,
  team_id uuid,
  location_id uuid,
  manager_id uuid,
  hr_manager_id uuid,
  employment_status USER-DEFINED NOT NULL DEFAULT 'ACTIVE'::employment_status_enum,
  probation_end_date date,
  notice_period_days integer,
  last_working_date date,
  official_email character varying UNIQUE,
  personal_email character varying,
  official_mobile character varying,
  personal_mobile character varying,
  nationality character varying DEFAULT 'Indian'::character varying,
  marital_status character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  blood_group character varying,
  grade character varying,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT employees_employment_type_id_fkey FOREIGN KEY (employment_type_id) REFERENCES public.employment_types(id),
  CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id),
  CONSTRAINT employees_designation_id_fkey FOREIGN KEY (designation_id) REFERENCES public.designations(id),
  CONSTRAINT employees_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT employees_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT employees_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.employees(id),
  CONSTRAINT employees_hr_manager_id_fkey FOREIGN KEY (hr_manager_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  change_type character varying NOT NULL,
  old_value jsonb,
  new_value jsonb,
  effective_date date NOT NULL,
  reason text,
  changed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_history_pkey PRIMARY KEY (id),
  CONSTRAINT employee_history_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_manager_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  manager_id uuid,
  effective_from date NOT NULL,
  effective_to date,
  is_current boolean NOT NULL DEFAULT true,
  changed_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_manager_history_pkey PRIMARY KEY (id),
  CONSTRAINT employee_manager_history_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_manager_history_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.employees(id),
  CONSTRAINT employee_manager_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.employees(id)
);
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  company_id uuid NOT NULL,
  location_id uuid,
  attendance_date date NOT NULL,
  shift_id uuid,
  scheduled_start timestamp with time zone,
  scheduled_end timestamp with time zone,
  check_in_at timestamp with time zone,
  check_out_at timestamp with time zone,
  check_in_latitude numeric,
  check_in_longitude numeric,
  check_in_accuracy numeric,
  check_out_latitude numeric,
  check_out_longitude numeric,
  check_out_accuracy numeric,
  worked_minutes integer NOT NULL DEFAULT 0,
  break_minutes integer NOT NULL DEFAULT 0,
  overtime_minutes integer NOT NULL DEFAULT 0,
  late_minutes integer NOT NULL DEFAULT 0,
  early_exit_minutes integer NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'ABSENT'::attendance_status_enum,
  source character varying NOT NULL DEFAULT 'MOBILE'::character varying,
  is_manual_adjustment boolean NOT NULL DEFAULT false,
  adjustment_reason text,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT attendance_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT attendance_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.shifts(id),
  CONSTRAINT attendance_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.attendance_exceptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attendance_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  exception_type character varying NOT NULL,
  description text,
  severity character varying NOT NULL DEFAULT 'LOW'::character varying,
  status character varying NOT NULL DEFAULT 'OPEN'::character varying,
  raised_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_by uuid,
  resolved_at timestamp with time zone,
  resolution_note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_exceptions_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_exceptions_attendance_id_fkey FOREIGN KEY (attendance_id) REFERENCES public.attendance(id),
  CONSTRAINT attendance_exceptions_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_exceptions_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.attendance_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attendance_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  approved_by uuid,
  old_values jsonb NOT NULL,
  new_values jsonb NOT NULL,
  reason text NOT NULL,
  status character varying NOT NULL DEFAULT 'PENDING'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_at timestamp with time zone,
  CONSTRAINT attendance_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_adjustments_attendance_id_fkey FOREIGN KEY (attendance_id) REFERENCES public.attendance(id),
  CONSTRAINT attendance_adjustments_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.employees(id),
  CONSTRAINT attendance_adjustments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.leave_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  is_paid boolean NOT NULL DEFAULT true,
  requires_document boolean NOT NULL DEFAULT false,
  allows_half_day boolean NOT NULL DEFAULT true,
  max_consecutive_days integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_types_pkey PRIMARY KEY (id),
  CONSTRAINT leave_types_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.leave_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  year smallint NOT NULL,
  opening_balance numeric NOT NULL DEFAULT 0,
  accrued numeric NOT NULL DEFAULT 0,
  used numeric NOT NULL DEFAULT 0,
  adjusted numeric NOT NULL DEFAULT 0,
  encashed numeric NOT NULL DEFAULT 0,
  closing_balance numeric DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_balances_pkey PRIMARY KEY (id),
  CONSTRAINT leave_balances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT leave_balances_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  leave_type_id uuid NOT NULL,
  from_date date NOT NULL,
  to_date date NOT NULL,
  total_days numeric NOT NULL,
  half_day_type character varying,
  reason text,
  attachment_document_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::leave_request_status_enum,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT leave_requests_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES public.leave_types(id),
  CONSTRAINT fk_leave_attachment FOREIGN KEY (attachment_document_id) REFERENCES public.employee_documents(id)
);
CREATE TABLE public.leave_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  leave_request_id uuid NOT NULL,
  approver_id uuid NOT NULL,
  approval_level smallint NOT NULL DEFAULT 1,
  action USER-DEFINED NOT NULL,
  comments text,
  acted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT leave_approvals_leave_request_id_fkey FOREIGN KEY (leave_request_id) REFERENCES public.leave_requests(id),
  CONSTRAINT leave_approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES public.employees(id)
);
CREATE TABLE public.salary_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  component_type USER-DEFINED NOT NULL,
  calculation_type character varying NOT NULL DEFAULT 'FIXED'::character varying,
  is_taxable boolean NOT NULL DEFAULT false,
  is_statutory boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT salary_components_pkey PRIMARY KEY (id),
  CONSTRAINT salary_components_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.salary_structures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT salary_structures_pkey PRIMARY KEY (id),
  CONSTRAINT salary_structures_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.payroll_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  payroll_month smallint NOT NULL CHECK (payroll_month >= 1 AND payroll_month <= 12),
  payroll_year smallint NOT NULL CHECK (payroll_year >= 2000 AND payroll_year <= 2100),
  period_start date NOT NULL,
  period_end date NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::payroll_run_status_enum,
  employee_count integer NOT NULL DEFAULT 0,
  gross_pay numeric NOT NULL DEFAULT 0,
  total_deductions numeric NOT NULL DEFAULT 0,
  net_pay numeric NOT NULL DEFAULT 0,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_runs_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_runs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT payroll_runs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id),
  CONSTRAINT payroll_runs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.payroll_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payroll_run_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  working_days integer NOT NULL DEFAULT 0,
  paid_days numeric NOT NULL DEFAULT 0,
  gross_salary numeric NOT NULL DEFAULT 0,
  total_earnings numeric NOT NULL DEFAULT 0,
  total_deductions numeric NOT NULL DEFAULT 0,
  net_salary numeric NOT NULL DEFAULT 0,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_items_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_items_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id),
  CONSTRAINT payroll_items_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.payslips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payroll_item_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  payroll_run_id uuid NOT NULL,
  payslip_number character varying NOT NULL DEFAULT ((('PAY-'::text || to_char(now(), 'YYYY-MM'::text)) || '-'::text) || lpad((nextval('payslip_number_seq'::regclass))::text, 4, '0'::text)) UNIQUE,
  gross_salary numeric NOT NULL,
  deductions numeric NOT NULL,
  net_salary numeric NOT NULL,
  payslip_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  pdf_storage_path text,
  generated_at timestamp with time zone,
  published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payslips_pkey PRIMARY KEY (id),
  CONSTRAINT payslips_payroll_item_id_fkey FOREIGN KEY (payroll_item_id) REFERENCES public.payroll_items(id),
  CONSTRAINT payslips_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payslips_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id)
);
CREATE TABLE public.asset_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  prefix character varying NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT asset_categories_pkey PRIMARY KEY (id),
  CONSTRAINT asset_categories_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.asset_brands (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name character varying NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT asset_brands_pkey PRIMARY KEY (id),
  CONSTRAINT asset_brands_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid,
  asset_category_id uuid NOT NULL,
  brand_id uuid,
  asset_code character varying NOT NULL UNIQUE,
  asset_tag character varying,
  model character varying,
  serial_number character varying UNIQUE,
  imei_1 character varying UNIQUE,
  mobile_number character varying UNIQUE,
  purchase_date date,
  purchase_cost numeric,
  warranty_start date,
  warranty_end date,
  condition character varying NOT NULL DEFAULT 'GOOD'::character varying,
  status USER-DEFINED NOT NULL DEFAULT 'AVAILABLE'::asset_status_enum,
  current_employee_id uuid,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  imei_2 character varying,
  sim_number character varying,
  vendor_name character varying,
  invoice_number character varying,
  CONSTRAINT assets_pkey PRIMARY KEY (id),
  CONSTRAINT assets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT assets_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT assets_asset_category_id_fkey FOREIGN KEY (asset_category_id) REFERENCES public.asset_categories(id),
  CONSTRAINT assets_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.asset_brands(id),
  CONSTRAINT assets_current_employee_id_fkey FOREIGN KEY (current_employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.asset_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_by uuid,
  expected_return_date date,
  returned_at timestamp with time zone,
  status character varying NOT NULL DEFAULT 'ACTIVE'::character varying,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT asset_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT asset_assignments_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT asset_assignments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT asset_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.employees(id)
);
CREATE TABLE public.document_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT document_types_pkey PRIMARY KEY (id),
  CONSTRAINT document_types_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.employee_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  document_type_id uuid NOT NULL,
  storage_path text NOT NULL,
  file_name character varying NOT NULL,
  mime_type character varying,
  file_size integer,
  issue_date date,
  expiry_date date,
  status character varying NOT NULL DEFAULT 'ACTIVE'::character varying,
  uploaded_by uuid,
  verified_by uuid,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  document_number_encrypted text,
  CONSTRAINT employee_documents_pkey PRIMARY KEY (id),
  CONSTRAINT employee_documents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_documents_document_type_id_fkey FOREIGN KEY (document_type_id) REFERENCES public.document_types(id),
  CONSTRAINT employee_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.employees(id),
  CONSTRAINT employee_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.employees(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_employee_id uuid NOT NULL,
  notification_type character varying NOT NULL,
  title character varying NOT NULL,
  body text NOT NULL,
  data jsonb,
  priority character varying NOT NULL DEFAULT 'NORMAL'::character varying,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  is_read boolean NOT NULL DEFAULT false,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_recipient_employee_id_fkey FOREIGN KEY (recipient_employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  code character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id),
  CONSTRAINT roles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  module character varying NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.employee_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  role_id uuid NOT NULL,
  company_id uuid NOT NULL,
  location_id uuid,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean NOT NULL DEFAULT true,
  assigned_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_roles_pkey PRIMARY KEY (id),
  CONSTRAINT employee_roles_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT employee_roles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT employee_roles_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT employee_roles_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.employees(id)
);
CREATE TABLE public.audit_logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  company_id uuid,
  actor_employee_id uuid,
  actor_auth_user_id uuid,
  action character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT audit_logs_actor_employee_id_fkey FOREIGN KEY (actor_employee_id) REFERENCES public.employees(id),
  CONSTRAINT audit_logs_actor_auth_user_id_fkey FOREIGN KEY (actor_auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  setting_key character varying NOT NULL,
  setting_value text NOT NULL,
  data_type character varying NOT NULL DEFAULT 'STRING'::character varying,
  description text,
  is_public boolean NOT NULL DEFAULT false,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id),
  CONSTRAINT system_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  account_holder_name character varying NOT NULL,
  bank_name character varying NOT NULL,
  account_number_encrypted text NOT NULL,
  account_number_last4 character varying NOT NULL,
  ifsc_code character varying NOT NULL,
  branch_name character varying,
  account_type character varying NOT NULL DEFAULT 'SAVINGS'::character varying,
  is_primary boolean NOT NULL DEFAULT true,
  is_verified boolean NOT NULL DEFAULT false,
  verified_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_bank_accounts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_statutory_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL UNIQUE,
  pan_encrypted text,
  pan_last4 character varying,
  uan character varying,
  pf_number character varying,
  esi_number character varying,
  professional_tax_number character varying,
  aadhaar_last4 character varying,
  tax_regime character varying DEFAULT 'NEW'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_statutory_details_pkey PRIMARY KEY (id),
  CONSTRAINT employee_statutory_details_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  contact_type character varying NOT NULL,
  contact_name character varying,
  relationship character varying,
  mobile character varying,
  email character varying,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_contacts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_emergency_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  name character varying NOT NULL,
  relationship character varying,
  mobile character varying NOT NULL,
  alternate_mobile character varying,
  address text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_emergency_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT employee_emergency_contacts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_salary_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  salary_structure_id uuid,
  annual_ctc numeric NOT NULL DEFAULT 0,
  monthly_ctc numeric DEFAULT (annual_ctc / (12)::numeric),
  effective_from date NOT NULL DEFAULT CURRENT_DATE,
  effective_to date,
  is_current boolean NOT NULL DEFAULT true,
  approved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_salary_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT employee_salary_assignments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_salary_assignments_salary_structure_id_fkey FOREIGN KEY (salary_structure_id) REFERENCES public.salary_structures(id),
  CONSTRAINT employee_salary_assignments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.asset_handover (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_assignment_id uuid NOT NULL,
  handover_date date NOT NULL DEFAULT CURRENT_DATE,
  employee_acknowledged boolean NOT NULL DEFAULT false,
  employee_signature_path text,
  handover_document_path text,
  condition_at_handover character varying,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT asset_handover_pkey PRIMARY KEY (id),
  CONSTRAINT asset_handover_asset_assignment_id_fkey FOREIGN KEY (asset_assignment_id) REFERENCES public.asset_assignments(id)
);
CREATE TABLE public.asset_returns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_assignment_id uuid NOT NULL,
  return_date date NOT NULL DEFAULT CURRENT_DATE,
  received_by uuid,
  condition_at_return character varying,
  damage_description text,
  missing_items text,
  recovery_amount numeric,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT asset_returns_pkey PRIMARY KEY (id),
  CONSTRAINT asset_returns_asset_assignment_id_fkey FOREIGN KEY (asset_assignment_id) REFERENCES public.asset_assignments(id),
  CONSTRAINT asset_returns_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.employees(id)
);
CREATE TABLE public.asset_maintenance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  maintenance_type character varying NOT NULL,
  vendor character varying,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  cost numeric,
  description text,
  status character varying NOT NULL DEFAULT 'OPEN'::character varying,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT asset_maintenance_pkey PRIMARY KEY (id),
  CONSTRAINT asset_maintenance_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.assets(id),
  CONSTRAINT asset_maintenance_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id)
);
CREATE TABLE public.idempotency_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  idempotency_key character varying NOT NULL,
  endpoint character varying NOT NULL,
  response_status integer NOT NULL,
  response_body jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id),
  CONSTRAINT idempotency_keys_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  expense_date date NOT NULL DEFAULT CURRENT_DATE,
  category character varying NOT NULL DEFAULT 'OTHER'::character varying,
  description text NOT NULL,
  amount numeric NOT NULL,
  receipt_path text,
  status character varying NOT NULL DEFAULT 'PENDING'::character varying,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT expenses_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT expenses_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.helpdesk_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  category character varying NOT NULL DEFAULT 'HR'::character varying,
  subject character varying NOT NULL,
  description text,
  priority character varying NOT NULL DEFAULT 'NORMAL'::character varying,
  status character varying NOT NULL DEFAULT 'OPEN'::character varying,
  assigned_to uuid,
  resolved_at timestamp with time zone,
  resolution text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT helpdesk_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT helpdesk_tickets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT helpdesk_tickets_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT helpdesk_tickets_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.employees(id)
);
CREATE TABLE public.resignations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  resignation_date date NOT NULL DEFAULT CURRENT_DATE,
  last_working_date date,
  reason text,
  status character varying NOT NULL DEFAULT 'SUBMITTED'::character varying,
  it_cleared boolean NOT NULL DEFAULT false,
  it_cleared_by uuid,
  it_cleared_at timestamp with time zone,
  finance_cleared boolean NOT NULL DEFAULT false,
  finance_cleared_by uuid,
  finance_cleared_at timestamp with time zone,
  hr_cleared boolean NOT NULL DEFAULT false,
  hr_cleared_by uuid,
  hr_cleared_at timestamp with time zone,
  ff_amount numeric,
  ff_notes text,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resignations_pkey PRIMARY KEY (id),
  CONSTRAINT resignations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT resignations_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT resignations_it_cleared_by_fkey FOREIGN KEY (it_cleared_by) REFERENCES public.employees(id),
  CONSTRAINT resignations_finance_cleared_by_fkey FOREIGN KEY (finance_cleared_by) REFERENCES public.employees(id),
  CONSTRAINT resignations_hr_cleared_by_fkey FOREIGN KEY (hr_cleared_by) REFERENCES public.employees(id),
  CONSTRAINT resignations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.custom_fields (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name character varying NOT NULL,
  field_type USER-DEFINED NOT NULL,
  options jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT custom_fields_pkey PRIMARY KEY (id),
  CONSTRAINT custom_fields_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.employee_custom_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id uuid NOT NULL,
  custom_field_id uuid NOT NULL,
  field_value jsonb NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_custom_data_pkey PRIMARY KEY (id),
  CONSTRAINT employee_custom_data_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_custom_data_custom_field_id_fkey FOREIGN KEY (custom_field_id) REFERENCES public.custom_fields(id)
);
CREATE TABLE public.attendance_punches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  attendance_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  company_id uuid NOT NULL,
  punch_type character varying NOT NULL CHECK (punch_type::text = ANY (ARRAY['IN'::character varying, 'OUT'::character varying, 'BREAK_IN'::character varying, 'BREAK_OUT'::character varying]::text[])),
  punch_at timestamp with time zone NOT NULL,
  latitude numeric,
  longitude numeric,
  accuracy numeric,
  source character varying NOT NULL DEFAULT 'MOBILE'::character varying,
  device_id character varying,
  device_name character varying,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_punches_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_punches_attendance_fkey FOREIGN KEY (attendance_id) REFERENCES public.attendance(id),
  CONSTRAINT attendance_punches_employee_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_punches_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.salary_structure_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  salary_structure_id uuid NOT NULL,
  salary_component_id uuid NOT NULL,
  calculation_type character varying NOT NULL DEFAULT 'FIXED'::character varying,
  amount numeric NOT NULL DEFAULT 0,
  percentage numeric,
  percentage_of_component_id uuid,
  sequence_no integer NOT NULL DEFAULT 1,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT salary_structure_components_pkey PRIMARY KEY (id),
  CONSTRAINT salary_structure_components_structure_fkey FOREIGN KEY (salary_structure_id) REFERENCES public.salary_structures(id),
  CONSTRAINT salary_structure_components_component_fkey FOREIGN KEY (salary_component_id) REFERENCES public.salary_components(id),
  CONSTRAINT salary_structure_components_percentage_component_fkey FOREIGN KEY (percentage_of_component_id) REFERENCES public.salary_components(id)
);
CREATE TABLE public.payroll_item_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payroll_item_id uuid NOT NULL,
  salary_component_id uuid NOT NULL,
  component_type character varying NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  calculation_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_item_components_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_item_components_item_fkey FOREIGN KEY (payroll_item_id) REFERENCES public.payroll_items(id),
  CONSTRAINT payroll_item_components_component_fkey FOREIGN KEY (salary_component_id) REFERENCES public.salary_components(id)
);
CREATE TABLE public.sim_cards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  sim_code character varying NOT NULL,
  mobile_number character varying,
  sim_number character varying,
  iccid character varying,
  imsi character varying,
  telecom_operator character varying,
  plan_name character varying,
  activation_date date,
  expiry_date date,
  status character varying NOT NULL DEFAULT 'AVAILABLE'::character varying CHECK (status::text = ANY (ARRAY['AVAILABLE'::character varying, 'ASSIGNED'::character varying, 'SUSPENDED'::character varying, 'LOST'::character varying, 'DAMAGED'::character varying, 'RETIRED'::character varying, 'DISPOSED'::character varying]::text[])),
  current_employee_id uuid,
  purchase_date date,
  purchase_cost numeric,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sim_cards_pkey PRIMARY KEY (id),
  CONSTRAINT sim_cards_company_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT sim_cards_employee_fkey FOREIGN KEY (current_employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.sim_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sim_card_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_by uuid,
  expected_return_date date,
  returned_at timestamp with time zone,
  status character varying NOT NULL DEFAULT 'ACTIVE'::character varying,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sim_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT sim_assignments_sim_fkey FOREIGN KEY (sim_card_id) REFERENCES public.sim_cards(id),
  CONSTRAINT sim_assignments_employee_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT sim_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_document_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_document_id uuid NOT NULL,
  version_number integer NOT NULL,
  storage_path text NOT NULL,
  file_name character varying NOT NULL,
  mime_type character varying,
  file_size integer,
  uploaded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT employee_document_versions_pkey PRIMARY KEY (id),
  CONSTRAINT employee_document_versions_document_fkey FOREIGN KEY (employee_document_id) REFERENCES public.employee_documents(id),
  CONSTRAINT employee_document_versions_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.employees(id)
);
CREATE TABLE public.exit_clearances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resignation_id uuid NOT NULL,
  clearance_department character varying NOT NULL,
  assigned_to uuid,
  status character varying NOT NULL DEFAULT 'PENDING'::character varying,
  remarks text,
  cleared_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exit_clearances_pkey PRIMARY KEY (id),
  CONSTRAINT exit_clearances_resignation_fkey FOREIGN KEY (resignation_id) REFERENCES public.resignations(id),
  CONSTRAINT exit_clearances_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.employees(id)
);